namespace O2SmsCli.O2;

static class O2ResponseType
{
  /*
   * Hodnoty na zaklade zmatene tabulky na strane 32 v manualu
   */

  /// <summary>
  /// One or more message parameters are in the wrong format
  /// </summary>
  public const string FORMAT_ERROR = "FORMAT_ERROR";

  /// <summary>
  /// Synchronous error related to authentication
  /// </summary>
  /// <remarks>Melo by to byt s podtrzitkem. Experimentralne overeno.</remarks>
  public const string AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR";

  /// <summary>
  /// A negative result of the message processing generated by the Business Application or MP either related to the content of the message or to the functionality.
  /// </summary>
  public const string APPL_ERROR = "APPL_ERROR";

  /// <summary>
  /// A serious error in the O2 Messaging Platform or in the BA in push mode.
  /// </summary>
  public const string INTERNAL_ERROR = "INTERNAL_ERROR";

  /// <summary>
  /// Synchronous responses for success and asynchronous deliveryReports.
  /// </summary>
  public const string SUCCESS = "SUCCESS";
}
