//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2SmsCli.O2.PPGwPort
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://b2b.eurotel.cz", ConfigurationName="O2SmsCli.O2.PPGwPort.PPGw")]
    internal interface PPGw
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.eurotel.cz/PPGw/send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Message))]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.sendResponse> sendAsync(O2SmsCli.O2.PPGwPort.send request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.eurotel.cz/PPGw/ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Message))]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.pingResponse> pingAsync(O2SmsCli.O2.PPGwPort.ping request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.eurotel.cz/PPGw/confirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Message))]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.confirmResponse> confirmAsync(O2SmsCli.O2.PPGwPort.confirm request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.eurotel.cz/PPGw/receiveWithTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Message))]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.receiveWithTimeResponse> receiveWithTimeAsync(O2SmsCli.O2.PPGwPort.receiveWithTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://b2b.eurotel.cz/PPGw/receive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Message))]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.receiveResponse> receiveAsync(O2SmsCli.O2.PPGwPort.receive request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class MessageContainer
    {
        
        private BinarySms binarySmsField;
        
        private Mms mmsField;
        
        private Response responseField;
        
        private string selectorField;
        
        private TextSms textSmsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public BinarySms binarySms
        {
            get
            {
                return this.binarySmsField;
            }
            set
            {
                this.binarySmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Mms mms
        {
            get
            {
                return this.mmsField;
            }
            set
            {
                this.mmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public Response response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string selector
        {
            get
            {
                return this.selectorField;
            }
            set
            {
                this.selectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public TextSms textSms
        {
            get
            {
                return this.textSmsField;
            }
            set
            {
                this.textSmsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class BinarySms : Sms
    {
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSms))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class Sms : Request
    {
        
        private int dataCodingSchemeField;
        
        private string fromNumberField;
        
        private byte[] headerField;
        
        private PremiumInfo premiumInfoField;
        
        private string protocolIdentifierField;
        
        private string reportLevelField;
        
        private string toNumberField;
        
        private long validityPeriodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dataCodingScheme
        {
            get
            {
                return this.dataCodingSchemeField;
            }
            set
            {
                this.dataCodingSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string fromNumber
        {
            get
            {
                return this.fromNumberField;
            }
            set
            {
                this.fromNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public PremiumInfo premiumInfo
        {
            get
            {
                return this.premiumInfoField;
            }
            set
            {
                this.premiumInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string protocolIdentifier
        {
            get
            {
                return this.protocolIdentifierField;
            }
            set
            {
                this.protocolIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string reportLevel
        {
            get
            {
                return this.reportLevelField;
            }
            set
            {
                this.reportLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string toNumber
        {
            get
            {
                return this.toNumberField;
            }
            set
            {
                this.toNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long validityPeriod
        {
            get
            {
                return this.validityPeriodField;
            }
            set
            {
                this.validityPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class PremiumInfo
    {
        
        private string billingCodeField;
        
        private string orderIDField;
        
        private string orderingChannelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string billingCode
        {
            get
            {
                return this.billingCodeField;
            }
            set
            {
                this.billingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string orderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string orderingChannel
        {
            get
            {
                return this.orderingChannelField;
            }
            set
            {
                this.orderingChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class MessageContainerWithTime
    {
        
        private BinarySmsWithTime binarySmsField;
        
        private Mms mmsField;
        
        private Response responseField;
        
        private string selectorField;
        
        private TextSmsWithTime textSmsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public BinarySmsWithTime binarySms
        {
            get
            {
                return this.binarySmsField;
            }
            set
            {
                this.binarySmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Mms mms
        {
            get
            {
                return this.mmsField;
            }
            set
            {
                this.mmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public Response response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string selector
        {
            get
            {
                return this.selectorField;
            }
            set
            {
                this.selectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public TextSmsWithTime textSms
        {
            get
            {
                return this.textSmsField;
            }
            set
            {
                this.textSmsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class BinarySmsWithTime : SmsWithTime
    {
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSmsWithTime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class SmsWithTime : Sms
    {
        
        private System.DateTime startTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class TextSmsWithTime : SmsWithTime
    {
        
        private bool intruderField;
        
        private bool multiPartField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool intruder
        {
            get
            {
                return this.intruderField;
            }
            set
            {
                this.intruderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool multiPart
        {
            get
            {
                return this.multiPartField;
            }
            set
            {
                this.multiPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class Mms : Request
    {
        
        private string fromNumberField;
        
        private string messageClassField;
        
        private MmsPart[] partsField;
        
        private PremiumInfo premiumInfoField;
        
        private string presentationField;
        
        private string reportLevelField;
        
        private string subjectField;
        
        private string toNumberField;
        
        private long validityPeriodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string fromNumber
        {
            get
            {
                return this.fromNumberField;
            }
            set
            {
                this.fromNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string messageClass
        {
            get
            {
                return this.messageClassField;
            }
            set
            {
                this.messageClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public MmsPart[] parts
        {
            get
            {
                return this.partsField;
            }
            set
            {
                this.partsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public PremiumInfo premiumInfo
        {
            get
            {
                return this.premiumInfoField;
            }
            set
            {
                this.premiumInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string presentation
        {
            get
            {
                return this.presentationField;
            }
            set
            {
                this.presentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string reportLevel
        {
            get
            {
                return this.reportLevelField;
            }
            set
            {
                this.reportLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string toNumber
        {
            get
            {
                return this.toNumberField;
            }
            set
            {
                this.toNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long validityPeriod
        {
            get
            {
                return this.validityPeriodField;
            }
            set
            {
                this.validityPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class MmsPart
    {
        
        private byte[] contentField;
        
        private string contentEncodingField;
        
        private string contentTypeField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string contentEncoding
        {
            get
            {
                return this.contentEncodingField;
            }
            set
            {
                this.contentEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mms))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class Request : Message
    {
        
        private string priorityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSmsWithTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextSms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mms))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class Message
    {
        
        private string baIDField;
        
        private string msgIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string baID
        {
            get
            {
                return this.baIDField;
            }
            set
            {
                this.baIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string msgID
        {
            get
            {
                return this.msgIDField;
            }
            set
            {
                this.msgIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class Response : Message
    {
        
        private string codeField;
        
        private string descriptionField;
        
        private string refBaIDField;
        
        private string refMsgIDField;
        
        private System.Nullable<System.DateTime> timestampField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string refBaID
        {
            get
            {
                return this.refBaIDField;
            }
            set
            {
                this.refBaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string refMsgID
        {
            get
            {
                return this.refMsgIDField;
            }
            set
            {
                this.refMsgIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b2b.eurotel.cz")]
    public partial class TextSms : Sms
    {
        
        private bool intruderField;
        
        private bool multiPartField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool intruder
        {
            get
            {
                return this.intruderField;
            }
            set
            {
                this.intruderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool multiPart
        {
            get
            {
                return this.multiPartField;
            }
            set
            {
                this.multiPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class send
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public O2SmsCli.O2.PPGwPort.MessageContainer mc;
        
        public send()
        {
        }
        
        public send(System.Xml.XmlElement Any, O2SmsCli.O2.PPGwPort.MessageContainer mc)
        {
            this.Any = Any;
            this.mc = mc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class sendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public O2SmsCli.O2.PPGwPort.Response result;
        
        public sendResponse()
        {
        }
        
        public sendResponse(O2SmsCli.O2.PPGwPort.Response result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ping", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class ping
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string baID;
        
        public ping()
        {
        }
        
        public ping(string baID)
        {
            this.baID = baID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pingResponse", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class pingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public O2SmsCli.O2.PPGwPort.Response result;
        
        public pingResponse()
        {
        }
        
        public pingResponse(O2SmsCli.O2.PPGwPort.Response result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirm", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class confirm
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string baID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string refBaID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string refMsgID;
        
        public confirm()
        {
        }
        
        public confirm(string baID, string refBaID, string refMsgID)
        {
            this.baID = baID;
            this.refBaID = refBaID;
            this.refMsgID = refMsgID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmResponse", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class confirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public O2SmsCli.O2.PPGwPort.Response result;
        
        public confirmResponse()
        {
        }
        
        public confirmResponse(O2SmsCli.O2.PPGwPort.Response result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveWithTime", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class receiveWithTime
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string baID;
        
        public receiveWithTime()
        {
        }
        
        public receiveWithTime(string baID)
        {
            this.baID = baID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveResponseWithTime", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class receiveWithTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public O2SmsCli.O2.PPGwPort.MessageContainerWithTime result;
        
        public receiveWithTimeResponse()
        {
        }
        
        public receiveWithTimeResponse(O2SmsCli.O2.PPGwPort.MessageContainerWithTime result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receive", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class receive
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string baID;
        
        public receive()
        {
        }
        
        public receive(string baID)
        {
            this.baID = baID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveResponse", WrapperNamespace="http://b2b.eurotel.cz", IsWrapped=true)]
    internal partial class receiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://b2b.eurotel.cz", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public O2SmsCli.O2.PPGwPort.MessageContainer result;
        
        public receiveResponse()
        {
        }
        
        public receiveResponse(O2SmsCli.O2.PPGwPort.MessageContainer result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface PPGwChannel : O2SmsCli.O2.PPGwPort.PPGw, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class PPGwClient : System.ServiceModel.ClientBase<O2SmsCli.O2.PPGwPort.PPGw>, O2SmsCli.O2.PPGwPort.PPGw
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PPGwClient() : 
                base(PPGwClient.GetDefaultBinding(), PPGwClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PPGwPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPGwClient(EndpointConfiguration endpointConfiguration) : 
                base(PPGwClient.GetBindingForEndpoint(endpointConfiguration), PPGwClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPGwClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PPGwClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPGwClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PPGwClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPGwClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.sendResponse> O2SmsCli.O2.PPGwPort.PPGw.sendAsync(O2SmsCli.O2.PPGwPort.send request)
        {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.sendResponse> sendAsync(System.Xml.XmlElement Any, O2SmsCli.O2.PPGwPort.MessageContainer mc)
        {
            O2SmsCli.O2.PPGwPort.send inValue = new O2SmsCli.O2.PPGwPort.send();
            inValue.Any = Any;
            inValue.mc = mc;
            return ((O2SmsCli.O2.PPGwPort.PPGw)(this)).sendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.pingResponse> O2SmsCli.O2.PPGwPort.PPGw.pingAsync(O2SmsCli.O2.PPGwPort.ping request)
        {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.pingResponse> pingAsync(string baID)
        {
            O2SmsCli.O2.PPGwPort.ping inValue = new O2SmsCli.O2.PPGwPort.ping();
            inValue.baID = baID;
            return ((O2SmsCli.O2.PPGwPort.PPGw)(this)).pingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.confirmResponse> O2SmsCli.O2.PPGwPort.PPGw.confirmAsync(O2SmsCli.O2.PPGwPort.confirm request)
        {
            return base.Channel.confirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.confirmResponse> confirmAsync(string baID, string refBaID, string refMsgID)
        {
            O2SmsCli.O2.PPGwPort.confirm inValue = new O2SmsCli.O2.PPGwPort.confirm();
            inValue.baID = baID;
            inValue.refBaID = refBaID;
            inValue.refMsgID = refMsgID;
            return ((O2SmsCli.O2.PPGwPort.PPGw)(this)).confirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.receiveWithTimeResponse> O2SmsCli.O2.PPGwPort.PPGw.receiveWithTimeAsync(O2SmsCli.O2.PPGwPort.receiveWithTime request)
        {
            return base.Channel.receiveWithTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.receiveWithTimeResponse> receiveWithTimeAsync(string baID)
        {
            O2SmsCli.O2.PPGwPort.receiveWithTime inValue = new O2SmsCli.O2.PPGwPort.receiveWithTime();
            inValue.baID = baID;
            return ((O2SmsCli.O2.PPGwPort.PPGw)(this)).receiveWithTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.receiveResponse> O2SmsCli.O2.PPGwPort.PPGw.receiveAsync(O2SmsCli.O2.PPGwPort.receive request)
        {
            return base.Channel.receiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<O2SmsCli.O2.PPGwPort.receiveResponse> receiveAsync(string baID)
        {
            O2SmsCli.O2.PPGwPort.receive inValue = new O2SmsCli.O2.PPGwPort.receive();
            inValue.baID = baID;
            return ((O2SmsCli.O2.PPGwPort.PPGw)(this)).receiveAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PPGwPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PPGwPort))
            {
                return new System.ServiceModel.EndpointAddress("https://smsconnector.cz.o2.com/smsconnector/services/PPGwPort");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PPGwClient.GetBindingForEndpoint(EndpointConfiguration.PPGwPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PPGwClient.GetEndpointAddress(EndpointConfiguration.PPGwPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PPGwPort,
        }
    }
}
